export const FORMATS = {
  ITEM_DEFAULT_FORMAT: {
    Id: 0,
    TokenId: "",
    Contract: "",
    Creator: "",
    DeleteFlag: false,
    Link: "",
    Status: 0,
    Created: "",
    PartitionName: "",
    Json: '{"en":{"name":"","owner":"","size":"","weight":"","workplace":"","location":"","station":"","genre":[],"type":[]}, "ja":{"name":"","owner":"","size":"","weight":"","workplace":"","location":"","station":"","genre":[],"type":[]}}',
    Price: 0,
    Updated: "",
    Name: "",
  },
  GALLARY_DEFAULT_FORMAT: {
    ChannelId: "",
    Created: "",
    Eoa: "",
    Id: 0,
    Imgurl: "",
    Json: '{"ja":{"name":"","workplace":"","location":"","station":"","profile":""},"en":{"name":"","workplace":"","location":"","station":"","profile":""}}',
    Name: "",
    PartitionName: "",
    Seed: "",
    Status: 1,
    Type: "",
    Updated: "",
    DeleteFlag: false,
  },
};
