import { router } from "../../module/common/router";
import { CONST } from "../../module/common/const";

export const LANG = {
  en: {
    common: "about BizenDAO",
    official_announce: "Official Announce",
    official_youtube_links: "Official YouTube links",
    official_manual: "official_manual(PDF)",
    creator: "Potters",
    operating_member: "BizenDAO operating member",
    official_link: "Official Links（How to use)",
    promotion_activities: "Promotion Activities",
    metaberse: " Metaverse",
    learn_more: "Learn More",
    activities_by_college_students: "Activities by College Students",
    HOME: "home",
    CREATORS: "creators",
    TOKENS: "tokens",
    COTENTS: "contents",
    ACCOUNT: "account",
    DONATE: "donate",
    META: "meta",
    METANAME: "item name",
    DESCRIPTION: "description",
    MAINIMAGE: "image file url（.jpeg or .png）",
    MOVURL: "3D data url（.glb)",
    EXTURL: "external url",
    ATTRIBUTES: "attributes",
    LABEL: "trait type",
    VALUE: "value",
    JSONLOAD: "JSON LOAD",
    JSONDOWNLOAD: "JSON DOWNLOAD",
    OPENVAULT: "open value",
    PICTTOOL: "img resize",
    PERMAWEB: "permaweb",
    JSONSAMPLE: "sample JSON",
    SUBDONATE: "SUBSTITUTE DONATION",
    DONATEPRICE: "DONATE PRICE",
    CASHBACK: "CASHBACK",
    DONOR: "DONOR",
    SUBDONAHIST: "substitute donation history",
    SELECTMES: "select",
    COPYED: " has been copied to the clipboard",
    COPYFAILED: "Copy failed",
    DONATEMESSAGE:
      "BizenDAO registered artists can donate on behalf of buyers here.<br /> You can also get cash back on gas costs.",
    SENDTOEOA: "Send this NFT to EOA",
    SENDNFTBEF: "Do you really want to send this NFT to ",
    SENDNFTAFT: "？",
    BURNNFT:
      "Do you really want to burn this NFT?\nTo delete, please enter 'BURN' in the input box below.",
    BURNED: "NFT Burned",
    BURN_STOP: "Burn transaction has aborted.",
    SENDED: "Sent NFT",
    CANTSEND: "Cannot send to this EOA",
    ARE_YOU_BUYER: ", Are you the one who purchased this product?　",
    REQUIRE_META_URL: "*Please specify the URL where the metadata is stored.",
    TRYING_TO_MINT:
      "Bizen DAO SBT is a contract that is tied to the soul of the work, so if a completely unrelated SBT is created, it may be deleted by the Admin.\nPlease note that these rules are intended to prevent mischief and abuse.",
    REQUIRE_DBIZ: "require " + CONST.DONATE_SYMBOL,
    INVALID_TOKENURI: " is an invalid tokenURI",
    CREATOR_ONLY: "This NFT MINT is limited to the artist",
    NOT_ENOUGH_DBIZ:
      "You don't have enough " + CONST.DONATE_SYMBOL + " to mint.",
    NOT_ENOUGH: " is not enough",
    MES1: "Please enter your donation amount",
    MES2: "Failed to get current price. Please wait for a while.",
    MES3: "Cashback amount is too large",
    MES4: " : Are you sure you want to send it?",
    MES5: " sent",
    ARE_YOU_TBA: "Do you really want to issue a TBA?",
    TBA_MAKE: "Issue TZA to this NFT.",
    MINT_THE_TOKENURI: "mint the NFT using the specified tokenURI.",
    MINT_TX_SEND: "MINT transaction has been issued.",
    MINT_TX_STOP: "MINT transaction was aborted.",
    WAIT_MINT_TX: "Please wait while the transaction completes",
    MEMBER_SBT_EXIST:
      "Membership card SBT cannot be issued. It may have already been issued.",
    MEMBER_NOT_PARMITTED:
      "Membership card SBT cannot be issued. It may not be allowed.",
    TBA_ISSUE_SUCCESS: "Issued TBA issue transaction",
    TBA_ISSUE_ABORT: "TBA issue transaction aborted",
    POINT_NOT_EXIST:
      CONST.DONATE_SYMBOL +
      " of 1point or more is required to issue a member SBT",
    ADD_CONFIRM: ":are you ok?",
    ADD_COMPLETE: ":complete.",
    DEL_CONFIRM: ":are you sure?",
    DEL_COMPLETE: ":deleted.",
    UPDATE_CONFIRM: ":are you sure?",
    UPDATE_COMPLETE: ":updated.",
    CAN_NOT_CREATE: "You can not create",
    CAN_NOT_W_CREATE: "Duplicate registration is not possible",
    CAN_NOT_UPDATE: "You can not update",
    CANT_UPLOAD_FILE:
      "You are trying to upload a file with an unknown extension. \nThis file may not be viewed correctly. \nPlease check whether the contents of the file are correct. ",
    UPLOAD_CONFIRM:
      "You are trying to upload this file. This file will be public forever.\nThis operation cannot be undone.\nAre you sure you want to upload this?",
    UPLOAD_SUCCESS:
      "has been uploaded. <br /> Please wait for a while until it is reflected on permaweb.",
    FAILED_TO_UPLOAD: "Failed to upload",
    CANCEL_TO_UPLOAD: "Cancel to upload",
    FAILED_TO_CHECK_FILE: "Failed to check file",
    UPLOAD_ERROR: "Upload error",
    STACK_RENAME_CONFIRM: " | trying to change the file name. Are you sure?",
    STACK_DELETE_CONFIRM: " | trying to delete the file. Are you sure?",
    APPROVED: "Your request has been approved.",
    NOT_APPROVED: "An invalid request was sent.",
    DIFFERENT_USER: "The connected wallet is different.",
  },
  ja: {
    common: "BIZENDAOとは",
    official_announce: "Officialアナウンス",
    official_youtube_links: "Official Youtube リンク",
    official_manual: "Official マニュアル(PDF)",
    creator: "陶芸家一覧",
    operating_member: "BizenDAO 運営Member",
    official_link: "Officialリンク（使い方）",
    promotion_activities: "備前焼振興活動",
    metaberse: "メタバース",
    learn_more: "備前焼をもっと知ろう",
    activities_by_college_students: "大学生による振興活動",
    HOME: "ホーム",
    CREATORS: "作家",
    TOKENS: "NFT",
    COTENTS: "記事",
    ACCOUNT: "ユーザ",
    DONATE: "寄付",
    META: "メタデータ",
    METANAME: "作品タイトル",
    DESCRIPTION: "概要",
    MAINIMAGE: "写真データのURL（.jpeg or .png）",
    MOVURL: "３DのURL（.glb)",
    EXTURL: "PDFのURL",
    ATTRIBUTES: "追加情報",
    LABEL: "小見出し",
    VALUE: "本文",
    JSONLOAD: "JSONを読み込む",
    JSONDOWNLOAD: "JSON DOWNLOAD",
    OPENVAULT: "ファイル倉庫を開く",
    PICTTOOL: "画像リサイズ",
    PERMAWEB: "パーマウェブ",
    JSONSAMPLE: "JSONサンプル",
    SUBDONATE: "代理寄付",
    DONATEPRICE: "寄付額",
    CASHBACK: "キャッシュバック",
    DONOR: "寄付者",
    SUBDONAHIST: "代理寄付履歴",
    SELECTMES: "選択してください",
    COPYED: "がクリップボードにコピーされました",
    COPYFAILED: "コピーに失敗しました",
    DONATEMESSAGE:
      "BizenDAO登録作家はこちらで購入者に代わって代理寄付が可能です。<br />またガス代としてキャッシュバックすることができます。",
    SENDTOEOA: "このNFTをEOA宛に送信します",
    SENDNFTBEF: "本当にこのNFTを",
    SENDNFTAFT: "に送信しますか？",
    BURNNFT:
      "NFTを完全に削除します。\nこの操作は取り消すことができません。\n本当にこのNFTをBURNしますか？\n削除する場合は以下の入力BOXに「BURN」と入力してください。",
    BURNED: "BURNしました。",
    BURN_STOP: "BURN操作を中断しました。",
    SENDED: "送信しました",
    CANTSEND: "このアドレスには送信できません",
    ARE_YOU_BUYER: " あなたはこちらの商品の購入者ですか？　",
    REQUIRE_META_URL: "※ メタデータが格納されているURLを指定してください。",
    TRYING_TO_MINT:
      "Bizen DAO SBTは作品の魂に紐付けるためのコントラクトですので、全く関連性のないSBTが作成された場合、Adminによって削除される事があります。\n悪戯と乱用を防ぐ為のルールですので、ご了承の上、ご利用ください。",
    REQUIRE_DBIZ: "必要な" + CONST.DONATE_SYMBOL,
    INVALID_TOKENURI: " は無効なtokenURIです。",
    CREATOR_ONLY: "このNFTのMINTは作家限定です。",
    NOT_ENOUGH_DBIZ:
      "Mintするのに必要な" + CONST.DONATE_SYMBOL + "が足りません。",
    NOT_ENOUGH: " が足りません。",
    MES1: "寄付額を入力してください",
    MES2: "現在価格の取得に失敗しました。しばらくお待ち下さい。",
    MES3: "キャッシュバック額が大きすぎます",
    MES4: "を送信してもよろしいですか？",
    MES5: "を送信しました。",
    ARE_YOU_TBA: "本当にTBAを発行しますか？",
    TBA_MAKE: "このNFTにTBAを発行します。",
    MINT_THE_TOKENURI: "指定したtokenURIを利用しNFTをMINTします。",
    MINT_TX_SEND: "MINTのトランザクションを発行しました。",
    MINT_TX_STOP: "MINTのトランザクションを中断しました。",
    WAIT_MINT_TX:
      "トランザクションの実行が完了するまでしばらくお待ちください。",
    MEMBER_SBT_EXIST: "会員証SBT発行不可 すでに発行済みの可能性があります。",
    MEMBER_NOT_PARMITTED: "会員証SBT発行権限がありません。",
    TBA_ISSUE_SUCCESS: "TBA発行トランザクションを発行しました。",
    TBA_ISSUE_ABORT: "TBA発行を中断しました。",
    POINT_NOT_EXIST:
      "メンバーズカード発行には1p以上の" + CONST.DONATE_SYMBOL + "が必要です。",
    ADD_CONFIRM: ":こちらを登録しますか？",
    ADD_COMPLEATE: ":こちらを登録しました。",
    DEL_CONFIRM: ":こちらを削除しますか?",
    DEL_COMPLETE: ":削除しました。",
    UPDATE_CONFIRM: ":こちらを更新しますか？",
    UPDATE_COMPLETE: ":更新しました。",
    CAN_NOT_CREATE: "登録できません",
    CAN_NOT_W_CREATE: "重複登録できません",
    CAN_NOT_UPDATE: "更新できません",
    CANT_UPLOAD_FILE:
      "\n不明な拡張子のファイルをアップロードしようとしています。\nこちらのファイルは正しく閲覧できない可能性があります。\nファイルの内容が正しいかご確認ください。",
    UPLOAD_CONFIRM:
      "こちらのファイルをアップロードしようとしています。\nこのファイルは永遠に公開され、この操作は取り消すことができません。\n本当にアップロードしてもよろしいですか。",
    UPLOAD_SUCCESS:
      "のアップロードが完了しました。<br /> permawebに反映されるまでしばらくお待ちください",
    FAILED_TO_UPLOAD: "アップロードに失敗しました。",
    CANCEL_TO_UPLOAD: "アップロードをキャンセルしました。",
    FAILED_TO_CHECK_FILE: "ファイルのチェックに失敗しました。",
    UPLOAD_ERROR: "アップロード中にエラーが発生しました。",
    STACK_RENAME_CONFIRM:
      " にリネームしようとしています。本当によろしいでしょうか？",
    STACK_DELETE_CONFIRM:
      " こちらのファイルを一覧から削除します。本当によろしいですか？\n一覧からの削除のみで本体のファイルを消すことはできません。",
    APPROVED: "あなたの購入証明は正しく認証されました。",
    NOT_APPROVED: "不正なリクエストが送信されました。",
    DIFFERENT_USER: "接続されているウォレットが違います。",
  },
};

export const LANGSET = (word: string) => {
  if (router.lang != "en" && router.lang != "ja") {
    return word;
  }
  const set = LANG[router.lang];
  return set[word];
};
